Document: couchdb-lounge
Title: Debian couchdb-lounge Manual
Author: <insert document author here>
Abstract: This manual describes what couchdb-lounge is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/couchdb-lounge/couchdb-lounge.sgml.gz

Format: postscript
Files: /usr/share/doc/couchdb-lounge/couchdb-lounge.ps.gz

Format: text
Files: /usr/share/doc/couchdb-lounge/couchdb-lounge.text.gz

Format: HTML
Index: /usr/share/doc/couchdb-lounge/html/index.html
Files: /usr/share/doc/couchdb-lounge/html/*.html
