#!/bin/sh
#
# chkconfig: 3 90 14
# Source function library.
. /etc/rc.d/init.d/functions

pidfile=/var/lounge/run/pid/dumbproxy.pid

start() {
	echo -n $"Starting Lounge Dumbproxy (NGINX): "
	daemon /var/lounge/sbin/nginx
	RETVAL=$?
	echo
	return $RETVAL
}

stop() {
	echo -n $"Stopping Lounge Dumbproxy (NGINX): "
	killproc -d 10 /var/lounge/sbin/nginx
	RETVAL=$?
	echo
	return $RETVAL
}

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
	status)
	status opinmindd.py
	;;
    restart)
	stop
	start
	;;
    condrestart)
	;;
    reload)
        ;;
    *)
	echo $"Usage: $0 {start|stop|restart|condrestart|reload}"
	;;
esac
exit $RETVAL
